import { StyleSheet } from "react-native";

import {
	BottomTabInset,
	MaxContentWidth,
	NakoTheme,
	Radius,
	Spacing,
} from "./theme";

export const ComponentStyles = StyleSheet.create({
	screen: {
		flex: 1,
		backgroundColor: NakoTheme.colors.background,
	},
	screenContent: {
		flex: 1,
		width: "100%",
		maxWidth: MaxContentWidth,
		paddingHorizontal: Spacing.four,
		paddingTop: Spacing.four,
		paddingBottom: BottomTabInset + Spacing.four,
	},
	section: {
		gap: Spacing.three,
	},
	row: {
		flexDirection: "row",
		alignItems: "center",
	},
	title: {
		color: NakoTheme.colors.textPrimary,
		fontFamily: NakoTheme.typography.fontFamily,
		fontSize: NakoTheme.typography.sizes.xl,
		fontWeight: NakoTheme.typography.weights.bold,
	},
	body: {
		color: NakoTheme.colors.textPrimary,
		fontFamily: NakoTheme.typography.fontFamily,
		fontSize: NakoTheme.typography.sizes.base,
		fontWeight: NakoTheme.typography.weights.medium,
		lineHeight: 24,
	},
	caption: {
		color: NakoTheme.colors.textSecondary,
		fontFamily: NakoTheme.typography.fontFamily,
		fontSize: NakoTheme.typography.sizes.sm,
		fontWeight: NakoTheme.typography.weights.medium,
		lineHeight: 20,
	},
	eyebrow: {
		color: NakoTheme.colors.textSecondary,
		fontFamily: NakoTheme.typography.fontFamily,
		fontSize: NakoTheme.typography.sizes.xs,
		fontWeight: NakoTheme.typography.weights.semibold,
		textTransform: "uppercase",
	},
	timerShell: {
		flex: 1,
		alignItems: "center",
		justifyContent: "center",
	},
	timerRing: {
		width: 280,
		height: 280,
		borderRadius: Radius.full,
		borderWidth: 18,
		borderColor: NakoTheme.colors.surface,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: NakoTheme.colors.background,
	},
	timerText: {
		color: NakoTheme.colors.textPrimary,
		fontFamily: NakoTheme.typography.fontFamily,
		fontSize: NakoTheme.typography.sizes.display,
		fontWeight: NakoTheme.typography.weights.bold,
		lineHeight: 90,
	},
	durationPicker: {
		flexDirection: "row",
		backgroundColor: NakoTheme.colors.surface,
		borderRadius: Radius.md,
		padding: NakoTheme.spacing.xs,
	},
	durationOption: {
		flex: 1,
		minHeight: 44,
		borderRadius: Radius.sm,
		alignItems: "center",
		justifyContent: "center",
	},
	durationOptionSelected: {
		backgroundColor: NakoTheme.colors.background,
	},
	durationText: {
		color: NakoTheme.colors.textSecondary,
		fontFamily: NakoTheme.typography.fontFamily,
		fontSize: NakoTheme.typography.sizes.sm,
		fontWeight: NakoTheme.typography.weights.semibold,
	},
	durationTextSelected: {
		color: NakoTheme.colors.primary,
	},
	primaryButton: {
		minHeight: 56,
		borderRadius: Radius.lg,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: NakoTheme.colors.primary,
		shadowColor: NakoTheme.colors.primary,
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.15,
		shadowRadius: 8,
	},
	dangerButton: {
		minHeight: 56,
		borderRadius: Radius.lg,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: NakoTheme.colors.danger,
	},
	secondaryButton: {
		minHeight: 56,
		borderRadius: Radius.lg,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: NakoTheme.colors.surface,
	},
	buttonText: {
		color: NakoTheme.colors.textInverted,
		fontFamily: NakoTheme.typography.fontFamily,
		fontSize: NakoTheme.typography.sizes.base,
		fontWeight: NakoTheme.typography.weights.semibold,
	},
	secondaryButtonText: {
		color: NakoTheme.colors.textPrimary,
		fontFamily: NakoTheme.typography.fontFamily,
		fontSize: NakoTheme.typography.sizes.base,
		fontWeight: NakoTheme.typography.weights.semibold,
	},
	summaryCard: {
		flexDirection: "row",
		borderWidth: 1,
		borderColor: NakoTheme.colors.border,
		borderRadius: Radius.lg,
		paddingVertical: Spacing.three,
	},
	summaryItem: {
		flex: 1,
		alignItems: "center",
		gap: Spacing.half,
	},
	summaryDivider: {
		width: 1,
		backgroundColor: NakoTheme.colors.border,
	},
	historyCard: {
		borderWidth: 1,
		borderColor: NakoTheme.colors.border,
		borderRadius: Radius.md,
		padding: Spacing.three,
		backgroundColor: NakoTheme.colors.background,
	},
	emptyState: {
		minHeight: 240,
		borderWidth: 1,
		borderColor: NakoTheme.colors.border,
		borderRadius: Radius.lg,
		alignItems: "center",
		justifyContent: "center",
		gap: Spacing.three,
		padding: Spacing.five,
	},
});
